### ISSUE TITLE
Wrong namespace

### ISSUE THREAD

**Issue by arcontact** [endroid/OpenWeatherMap#4]
Wrong namespacing in docs:
use Endroid\OpenWeatherMap\Client;
should be:
use Endroid\OpenWeatherMap\OpenWeatherMap;

$client = new Client($apiKey);
should be:
$client = new OpenWeatherMap($apiKey);

**Comment by endroid** [comment]
Hi @arcontact. The class name was changed from OpenWeatherMap to Client since 1.0.5.
